#!/usr/bin/env node
// Assembles catalog/research-log.md from:
//   1. research/log-notes.md   — the curator's narrative (sessions, totals,
//      saturation evidence). Hand-written.
//   2. research/raw/round-*/T*.json — each discovery track's logMd fragment.
//   3. research/manifests/*.json    — each inspection's logMd fragment.

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from '../lib/index-io.mjs';

const parts = [];
parts.push('# Research log');
parts.push('');
parts.push('<!-- GENERATED by scripts/research/build-log.mjs from research/log-notes.md,');
parts.push('     research/raw/**.json and research/manifests/*.json. Edit those sources. -->');
parts.push('');

const notes = join(ROOT, 'research', 'log-notes.md');
if (existsSync(notes)) {
  parts.push(readFileSync(notes, 'utf8').trim());
  parts.push('');
}

const rawDir = join(ROOT, 'research', 'raw');
if (existsSync(rawDir)) {
  parts.push('## Discovery sessions');
  parts.push('');
  for (const round of readdirSync(rawDir).sort()) {
    for (const file of readdirSync(join(rawDir, round)).sort()) {
      if (!file.endsWith('.json')) continue;
      const data = JSON.parse(readFileSync(join(rawDir, round, file), 'utf8'));
      if (data.logMd) {
        parts.push(data.logMd.trim());
        parts.push('');
      }
    }
  }
}

const manifestDir = join(ROOT, 'research', 'manifests');
if (existsSync(manifestDir)) {
  const files = readdirSync(manifestDir).filter((f) => f.endsWith('.json')).sort();
  if (files.length > 0) {
    parts.push('## Inspection sessions');
    parts.push('');
    for (const file of files) {
      const m = JSON.parse(readFileSync(join(manifestDir, file), 'utf8'));
      if (m.logMd) {
        parts.push(m.logMd.trim());
        parts.push('');
      }
    }
  }
}

writeFileSync(join(ROOT, 'catalog', 'research-log.md'), parts.join('\n'));
console.log('wrote catalog/research-log.md');
